"""Diverse Startup Seed Agent — provides curated startup data from top VC portfolios beyond YC."""
from __future__ import annotations
from models import Job, Founder


def get_diverse_seed_jobs() -> list[Job]:
    """Return curated list of well-known VC-backed startups for data diversity."""
    startups = [
        # ── A16Z Portfolio ────────────────────────────────
        {
            "company_name": "Mistral AI",
            "company_website": "https://mistral.ai",
            "company_slug": "mistral-ai",
            "stage": "Series B",
            "funding_total": "$528M",
            "team_size": 60,
            "founded_year": 2023,
            "country": "France",
            "city": "Paris",
            "vc_backers": ["a16z", "Lightspeed", "General Catalyst"],
            "industry_tags": ["AI", "LLM", "Open Source"],
            "founders": [
                {"name": "Arthur Mensch", "title": "CEO", "linkedin": "https://linkedin.com/in/arthur-mensch", "twitter": "https://twitter.com/arthurmensch"},
                {"name": "Guillaume Lample", "title": "CSO", "linkedin": "https://linkedin.com/in/guillaume-lample"},
                {"name": "Timothée Lacroix", "title": "CTO", "linkedin": "https://linkedin.com/in/timothee-lacroix"},
            ],
            "roles": [
                {"title": "Senior ML Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "€80K–€150K", "work_type": "hybrid"},
                {"title": "Research Scientist", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "€90K–€160K", "work_type": "onsite"},
                {"title": "Infrastructure Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "€70K–€120K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Anysphere",
            "company_website": "https://anysphere.inc",
            "company_slug": "anysphere",
            "stage": "Series B",
            "funding_total": "$900M",
            "team_size": 50,
            "founded_year": 2022,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Thrive Capital", "Founders Fund"],
            "industry_tags": ["AI", "Developer Tools", "IDE"],
            "founders": [
                {"name": "Michael Truell", "title": "CEO", "linkedin": "https://linkedin.com/in/michael-truell", "twitter": "https://twitter.com/michaeltruell"},
                {"name": "Sualeh Asif", "title": "CTO", "linkedin": "https://linkedin.com/in/sualeh-asif"},
                {"name": "Arvid Lunnemark", "title": "Co-founder", "linkedin": "https://linkedin.com/in/arvid-lunnemark"},
                {"name": "Aman Sanger", "title": "Co-founder", "linkedin": "https://linkedin.com/in/aman-sanger"},
            ],
            "roles": [
                {"title": "Full-Stack Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$180K–$300K", "work_type": "onsite"},
                {"title": "ML Research Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$350K", "work_type": "onsite"},
            ],
        },
        {
            "company_name": "ElevenLabs",
            "company_website": "https://elevenlabs.io",
            "company_slug": "elevenlabs",
            "stage": "Series B",
            "funding_total": "$180M",
            "team_size": 150,
            "founded_year": 2022,
            "country": "US",
            "city": "New York",
            "vc_backers": ["a16z", "Nat Friedman", "Daniel Gross"],
            "industry_tags": ["AI", "Audio", "Speech Synthesis"],
            "founders": [
                {"name": "Piotr Dąbkowski", "title": "CEO", "linkedin": "https://linkedin.com/in/piotr-dabkowski", "twitter": "https://twitter.com/paborismus"},
                {"name": "Mati Staniszewski", "title": "CTO", "linkedin": "https://linkedin.com/in/mati-staniszewski", "twitter": "https://twitter.com/mattstanis"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "remote"},
                {"title": "ML Engineer — Voice Cloning", "category": "AI/ML", "level": "Mid", "visa": "Yes", "salary": "$160K–$260K", "work_type": "hybrid"},
                {"title": "Product Designer", "category": "Design", "level": "Mid", "visa": "No", "salary": "$140K–$200K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Ramp",
            "company_website": "https://ramp.com",
            "company_slug": "ramp",
            "stage": "Series D",
            "funding_total": "$1.2B",
            "team_size": 800,
            "founded_year": 2019,
            "country": "US",
            "city": "New York",
            "vc_backers": ["a16z", "Founders Fund", "Thrive Capital", "Stripe"],
            "industry_tags": ["Fintech", "Expense Management", "Corporate Cards"],
            "founders": [
                {"name": "Eric Glyman", "title": "CEO", "linkedin": "https://linkedin.com/in/ericglyman", "twitter": "https://twitter.com/ericglyman"},
                {"name": "Karim Atiyeh", "title": "CTO", "linkedin": "https://linkedin.com/in/karimatiyeh"},
            ],
            "roles": [
                {"title": "Senior Software Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$260K", "work_type": "hybrid"},
                {"title": "Data Scientist", "category": "Data", "level": "Mid", "visa": "Yes", "salary": "$150K–$220K", "work_type": "onsite"},
                {"title": "Product Manager", "category": "GTM", "level": "Senior", "visa": "No", "salary": "$170K–$250K", "work_type": "hybrid"},
            ],
        },
        # ── Sequoia Portfolio ─────────────────────────────
        {
            "company_name": "Stripe",
            "company_website": "https://stripe.com",
            "company_slug": "stripe",
            "stage": "Growth",
            "funding_total": "$8.7B",
            "team_size": 8000,
            "founded_year": 2010,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "a16z", "General Catalyst"],
            "industry_tags": ["Fintech", "Payments", "Developer Tools"],
            "founders": [
                {"name": "Patrick Collison", "title": "CEO", "linkedin": "https://linkedin.com/in/patrickcollison", "twitter": "https://twitter.com/patrickc"},
                {"name": "John Collison", "title": "President", "linkedin": "https://linkedin.com/in/johncollison", "twitter": "https://twitter.com/collision"},
            ],
            "roles": [
                {"title": "Software Engineer — Payments", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$180K–$300K", "work_type": "hybrid"},
                {"title": "ML Engineer — Fraud Detection", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$350K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Scale AI",
            "company_website": "https://scale.com",
            "company_slug": "scale-ai",
            "stage": "Series F",
            "funding_total": "$1.6B",
            "team_size": 600,
            "founded_year": 2016,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "Accel", "Tiger Global", "Founders Fund"],
            "industry_tags": ["AI", "Data Labeling", "Enterprise"],
            "founders": [
                {"name": "Alexandr Wang", "title": "CEO", "linkedin": "https://linkedin.com/in/alexandrwang", "twitter": "https://twitter.com/alexandr_wang"},
                {"name": "Lucy Guo", "title": "Co-founder", "linkedin": "https://linkedin.com/in/lucy-guo", "twitter": "https://twitter.com/lucy_guo"},
            ],
            "roles": [
                {"title": "Senior ML Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "hybrid"},
                {"title": "Enterprise Account Executive", "category": "GTM", "level": "Senior", "visa": "No", "salary": "$150K–$300K OTE", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Wiz",
            "company_website": "https://wiz.io",
            "company_slug": "wiz",
            "stage": "Series D",
            "funding_total": "$900M",
            "team_size": 1200,
            "founded_year": 2020,
            "country": "US",
            "city": "New York",
            "vc_backers": ["Sequoia", "Insight Partners", "Index Ventures"],
            "industry_tags": ["Cloud Security", "DevSecOps", "Enterprise"],
            "founders": [
                {"name": "Assaf Rappaport", "title": "CEO", "linkedin": "https://linkedin.com/in/assafrappaport", "twitter": "https://twitter.com/assaborappaport"},
                {"name": "Ami Luttwak", "title": "CTO", "linkedin": "https://linkedin.com/in/ami-luttwak"},
                {"name": "Yinon Costica", "title": "VP Product", "linkedin": "https://linkedin.com/in/yinon-costica"},
                {"name": "Roy Reznik", "title": "VP R&D", "linkedin": "https://linkedin.com/in/royreznik"},
            ],
            "roles": [
                {"title": "Cloud Security Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid"},
                {"title": "Backend Engineer — Go", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "onsite"},
            ],
        },
        # ── Lightspeed Portfolio ──────────────────────────
        {
            "company_name": "Together AI",
            "company_website": "https://together.ai",
            "company_slug": "together-ai",
            "stage": "Series A",
            "funding_total": "$228M",
            "team_size": 100,
            "founded_year": 2022,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Lightspeed", "a16z", "Emergence Capital"],
            "industry_tags": ["AI", "Cloud Infrastructure", "Open Source"],
            "founders": [
                {"name": "Vipul Ved Prakash", "title": "CEO", "linkedin": "https://linkedin.com/in/vipul", "twitter": "https://twitter.com/vipulvedprakash"},
                {"name": "Ce Zhang", "title": "Chief Scientist", "linkedin": "https://linkedin.com/in/cezhang"},
            ],
            "roles": [
                {"title": "GPU Systems Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "hybrid"},
                {"title": "Frontend Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Rippling",
            "company_website": "https://rippling.com",
            "company_slug": "rippling",
            "stage": "Series F",
            "funding_total": "$1.2B",
            "team_size": 3000,
            "founded_year": 2016,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Lightspeed", "Sequoia", "Founders Fund", "Bedrock"],
            "industry_tags": ["HR Tech", "Payroll", "Enterprise SaaS"],
            "founders": [
                {"name": "Parker Conrad", "title": "CEO", "linkedin": "https://linkedin.com/in/parkerconrad", "twitter": "https://twitter.com/parkerconrad"},
            ],
            "roles": [
                {"title": "Software Engineer — Platform", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "hybrid"},
                {"title": "Senior Product Designer", "category": "Design", "level": "Senior", "visa": "Yes", "salary": "$170K–$240K", "work_type": "hybrid"},
            ],
        },
        # ── Founders Fund Portfolio ───────────────────────
        {
            "company_name": "Palantir Technologies",
            "company_website": "https://palantir.com",
            "company_slug": "palantir",
            "stage": "Growth",
            "funding_total": "$3.4B",
            "team_size": 3800,
            "founded_year": 2003,
            "country": "US",
            "city": "Denver",
            "vc_backers": ["Founders Fund", "In-Q-Tel"],
            "industry_tags": ["AI", "Big Data", "Government", "Enterprise"],
            "founders": [
                {"name": "Alexander Karp", "title": "CEO", "linkedin": "https://linkedin.com/in/alexander-karp", "twitter": "https://twitter.com/alexkarp"},
                {"name": "Peter Thiel", "title": "Chairman", "linkedin": "https://linkedin.com/in/peterthiel"},
            ],
            "roles": [
                {"title": "Forward Deployed Engineer", "category": "Engineering", "level": "New Grad", "visa": "Yes", "salary": "$120K–$180K", "work_type": "onsite"},
                {"title": "AI Platform Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Anduril Industries",
            "company_website": "https://anduril.com",
            "company_slug": "anduril",
            "stage": "Series F",
            "funding_total": "$3.7B",
            "team_size": 2500,
            "founded_year": 2017,
            "country": "US",
            "city": "Costa Mesa",
            "vc_backers": ["Founders Fund", "a16z", "General Catalyst"],
            "industry_tags": ["Defense Tech", "AI", "Autonomous Systems"],
            "founders": [
                {"name": "Palmer Luckey", "title": "Founder", "linkedin": "https://linkedin.com/in/palmer-luckey", "twitter": "https://twitter.com/PalmerLuckey"},
                {"name": "Brian Schimpf", "title": "CEO", "linkedin": "https://linkedin.com/in/brianschimpf"},
                {"name": "Trae Stephens", "title": "Chairman", "linkedin": "https://linkedin.com/in/traestephens", "twitter": "https://twitter.com/traestephens"},
            ],
            "roles": [
                {"title": "Robotics Software Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$260K", "work_type": "onsite"},
                {"title": "Computer Vision Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$180K–$300K", "work_type": "onsite"},
            ],
        },
        # ── Pearl / General Catalyst ──────────────────────
        {
            "company_name": "Glean",
            "company_website": "https://glean.com",
            "company_slug": "glean",
            "stage": "Series D",
            "funding_total": "$360M",
            "team_size": 500,
            "founded_year": 2019,
            "country": "US",
            "city": "Palo Alto",
            "vc_backers": ["General Catalyst", "Sequoia", "KPCB", "Lightspeed"],
            "industry_tags": ["AI", "Enterprise Search", "Knowledge Management"],
            "founders": [
                {"name": "Arvind Jain", "title": "CEO", "linkedin": "https://linkedin.com/in/arvindjain", "twitter": "https://twitter.com/arvindjain"},
            ],
            "roles": [
                {"title": "Senior Full-Stack Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "hybrid"},
                {"title": "NLP Research Engineer", "category": "AI/ML", "level": "Mid", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Vercel",
            "company_website": "https://vercel.com",
            "company_slug": "vercel",
            "stage": "Series D",
            "funding_total": "$563M",
            "team_size": 450,
            "founded_year": 2015,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Bedrock", "GV", "Tiger Global"],
            "industry_tags": ["Developer Tools", "Web Infrastructure", "JAMstack"],
            "founders": [
                {"name": "Guillermo Rauch", "title": "CEO", "linkedin": "https://linkedin.com/in/guillermo-rauch", "twitter": "https://twitter.com/raaborismo"},
            ],
            "roles": [
                {"title": "Software Engineer — Next.js", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$170K–$260K", "work_type": "remote"},
                {"title": "DevRel Engineer", "category": "GTM", "level": "Mid", "visa": "No", "salary": "$140K–$200K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Perplexity AI",
            "company_website": "https://perplexity.ai",
            "company_slug": "perplexity-ai",
            "stage": "Series B",
            "funding_total": "$250M",
            "team_size": 80,
            "founded_year": 2022,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Bessemer", "IVP", "NEA", "Jeff Bezos"],
            "industry_tags": ["AI", "Search", "LLM"],
            "founders": [
                {"name": "Aravind Srinivas", "title": "CEO", "linkedin": "https://linkedin.com/in/aravind-srinivas", "twitter": "https://twitter.com/AravSrinivas"},
                {"name": "Denis Yarats", "title": "CTO", "linkedin": "https://linkedin.com/in/denisyarats"},
                {"name": "Johnny Ho", "title": "CSO", "linkedin": "https://linkedin.com/in/johnny-ho"},
                {"name": "Andy Konwinski", "title": "Co-founder", "linkedin": "https://linkedin.com/in/andykonwinski"},
            ],
            "roles": [
                {"title": "Senior ML Engineer — Search", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$220K–$380K", "work_type": "onsite"},
                {"title": "Backend Engineer — Rust/Go", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$180K–$300K", "work_type": "onsite"},
                {"title": "Product Designer", "category": "Design", "level": "Mid", "visa": "No", "salary": "$150K–$220K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Databricks",
            "company_website": "https://databricks.com",
            "company_slug": "databricks",
            "stage": "Series I",
            "funding_total": "$4.1B",
            "team_size": 6000,
            "founded_year": 2013,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Bessemer", "Coatue", "Tiger Global"],
            "industry_tags": ["Data", "AI", "Analytics", "Enterprise"],
            "founders": [
                {"name": "Ali Ghodsi", "title": "CEO", "linkedin": "https://linkedin.com/in/alighodsi", "twitter": "https://twitter.com/aaborimpf"},
            ],
            "roles": [
                {"title": "Staff Software Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$220K–$360K", "work_type": "hybrid"},
                {"title": "Data Engineer", "category": "Data", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "hybrid"},
            ],
        },
        # ── Bessemer Portfolio ────────────────────────────
        {
            "company_name": "Canva",
            "company_website": "https://canva.com",
            "company_slug": "canva",
            "stage": "Growth",
            "funding_total": "$572M",
            "team_size": 4000,
            "founded_year": 2012,
            "country": "Australia",
            "city": "Sydney",
            "vc_backers": ["Bessemer", "Sequoia", "Felicis", "Blackbird"],
            "industry_tags": ["Design", "SaaS", "Creative Tools"],
            "founders": [
                {"name": "Melanie Perkins", "title": "CEO", "linkedin": "https://linkedin.com/in/melanieperkins", "twitter": "https://twitter.com/MelanieCanva"},
                {"name": "Cliff Obrecht", "title": "COO", "linkedin": "https://linkedin.com/in/cliff-obrecht"},
                {"name": "Cameron Adams", "title": "CPO", "linkedin": "https://linkedin.com/in/cameron-adams", "twitter": "https://twitter.com/themaninblue"},
            ],
            "roles": [
                {"title": "Frontend Engineer — React", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "AUD $130K–$190K", "work_type": "hybrid"},
                {"title": "AI/ML Engineer — Visual AI", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "AUD $160K–$230K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Deel",
            "company_website": "https://deel.com",
            "company_slug": "deel",
            "stage": "Series D",
            "funding_total": "$679M",
            "team_size": 3000,
            "founded_year": 2019,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Spark Capital", "Coatue"],
            "industry_tags": ["HR Tech", "Global Payroll", "Remote Work"],
            "founders": [
                {"name": "Alex Bouaziz", "title": "CEO", "linkedin": "https://linkedin.com/in/abouaziz", "twitter": "https://twitter.com/alexbouaziz"},
                {"name": "Shuo Wang", "title": "CRO", "linkedin": "https://linkedin.com/in/shuo-wang"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$170K–$260K", "work_type": "remote"},
                {"title": "Compliance Specialist", "category": "Ops", "level": "Mid", "visa": "No", "salary": "$100K–$150K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Figma",
            "company_website": "https://figma.com",
            "company_slug": "figma",
            "stage": "Growth",
            "funding_total": "$332M",
            "team_size": 1200,
            "founded_year": 2012,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Sequoia", "KPCB", "Greylock"],
            "industry_tags": ["Design", "Collaboration Tools", "SaaS"],
            "founders": [
                {"name": "Dylan Field", "title": "CEO", "linkedin": "https://linkedin.com/in/dylanfield", "twitter": "https://twitter.com/zoink"},
                {"name": "Evan Wallace", "title": "Co-founder", "linkedin": "https://linkedin.com/in/evan-wallace"},
            ],
            "roles": [
                {"title": "Software Engineer — WebGL", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid"},
                {"title": "Design Systems Lead", "category": "Design", "level": "Senior", "visa": "Yes", "salary": "$190K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Linear",
            "company_website": "https://linear.app",
            "company_slug": "linear",
            "stage": "Series B",
            "funding_total": "$52M",
            "team_size": 70,
            "founded_year": 2019,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "01 Advisors"],
            "industry_tags": ["Developer Tools", "Project Management", "SaaS"],
            "founders": [
                {"name": "Karri Saarinen", "title": "CEO", "linkedin": "https://linkedin.com/in/karrisaarinen", "twitter": "https://twitter.com/karrisaarinen"},
                {"name": "Tuomas Artman", "title": "CTO", "linkedin": "https://linkedin.com/in/tuomasartman", "twitter": "https://twitter.com/tmsartman"},
                {"name": "Jori Lallo", "title": "Co-founder", "linkedin": "https://linkedin.com/in/jorilallo"},
            ],
            "roles": [
                {"title": "Product Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$260K", "work_type": "remote"},
            ],
        },
        # ── More Diverse Startups ─────────────────────────
        {
            "company_name": "Cohere",
            "company_website": "https://cohere.com",
            "company_slug": "cohere",
            "stage": "Series D",
            "funding_total": "$970M",
            "team_size": 400,
            "founded_year": 2019,
            "country": "Canada",
            "city": "Toronto",
            "vc_backers": ["Lightspeed", "NVIDIA", "Salesforce Ventures", "OMERS"],
            "industry_tags": ["AI", "LLM", "Enterprise AI"],
            "founders": [
                {"name": "Aidan Gomez", "title": "CEO", "linkedin": "https://linkedin.com/in/aidangomez", "twitter": "https://twitter.com/AidanOGomez"},
                {"name": "Ivan Zhang", "title": "COO", "linkedin": "https://linkedin.com/in/ivanzh"},
                {"name": "Nick Chicken Frosst", "title": "President", "linkedin": "https://linkedin.com/in/nickfrosst"},
            ],
            "roles": [
                {"title": "Research Engineer — NLP", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "CAD $180K–$280K", "work_type": "hybrid"},
                {"title": "Solutions Architect", "category": "GTM", "level": "Mid", "visa": "Yes", "salary": "CAD $120K–$180K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Notion",
            "company_website": "https://notion.so",
            "company_slug": "notion",
            "stage": "Series C",
            "funding_total": "$343M",
            "team_size": 600,
            "founded_year": 2013,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "Index Ventures", "Coatue"],
            "industry_tags": ["Productivity", "Collaboration", "SaaS"],
            "founders": [
                {"name": "Ivan Zhao", "title": "CEO", "linkedin": "https://linkedin.com/in/ivan-zhao", "twitter": "https://twitter.com/ivankzhao"},
                {"name": "Simon Last", "title": "Co-founder", "linkedin": "https://linkedin.com/in/simonlast"},
            ],
            "roles": [
                {"title": "Senior Software Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$195K–$300K", "work_type": "hybrid"},
                {"title": "AI Product Manager", "category": "GTM", "level": "Senior", "visa": "No", "salary": "$180K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Hugging Face",
            "company_website": "https://huggingface.co",
            "company_slug": "hugging-face",
            "stage": "Series D",
            "funding_total": "$395M",
            "team_size": 250,
            "founded_year": 2016,
            "country": "US",
            "city": "New York",
            "vc_backers": ["a16z", "Sequoia", "Coatue", "Lux Capital"],
            "industry_tags": ["AI", "Open Source", "ML Platform"],
            "founders": [
                {"name": "Clément Delangue", "title": "CEO", "linkedin": "https://linkedin.com/in/clementdelangue", "twitter": "https://twitter.com/ClementDelangue"},
                {"name": "Julien Chaumond", "title": "CTO", "linkedin": "https://linkedin.com/in/julienchaumond", "twitter": "https://twitter.com/julien_c"},
            ],
            "roles": [
                {"title": "ML Infrastructure Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$260K", "work_type": "remote"},
                {"title": "Open Source Community Manager", "category": "GTM", "level": "Mid", "visa": "No", "salary": "$120K–$180K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Anthropic",
            "company_website": "https://anthropic.com",
            "company_slug": "anthropic",
            "stage": "Series E",
            "funding_total": "$11.5B",
            "team_size": 900,
            "founded_year": 2021,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Google", "Spark Capital", "Salesforce Ventures"],
            "industry_tags": ["AI", "AI Safety", "LLM"],
            "founders": [
                {"name": "Dario Amodei", "title": "CEO", "linkedin": "https://linkedin.com/in/darioamodei", "twitter": "https://twitter.com/DarioAmodei"},
                {"name": "Daniela Amodei", "title": "President", "linkedin": "https://linkedin.com/in/daniela-amodei"},
            ],
            "roles": [
                {"title": "Research Engineer — Alignment", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$250K–$400K", "work_type": "onsite"},
                {"title": "Software Engineer — Claude", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$200K–$350K", "work_type": "hybrid"},
                {"title": "Technical Program Manager", "category": "Ops", "level": "Senior", "visa": "No", "salary": "$180K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Supabase",
            "company_website": "https://supabase.com",
            "company_slug": "supabase",
            "stage": "Series C",
            "funding_total": "$116M",
            "team_size": 150,
            "founded_year": 2020,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Lightspeed", "Felicis", "Coatue"],
            "industry_tags": ["Developer Tools", "Database", "Open Source"],
            "founders": [
                {"name": "Paul Copplestone", "title": "CEO", "linkedin": "https://linkedin.com/in/paulcopplestone", "twitter": "https://twitter.com/kiwicopple"},
                {"name": "Ant Wilson", "title": "CTO", "linkedin": "https://linkedin.com/in/antwilson", "twitter": "https://twitter.com/antwilson"},
            ],
            "roles": [
                {"title": "Backend Engineer — Postgres", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$170K–$260K", "work_type": "remote"},
                {"title": "Developer Advocate", "category": "GTM", "level": "Mid", "visa": "No", "salary": "$130K–$180K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Zip (Procurement)",
            "company_website": "https://ziphq.com",
            "company_slug": "zip-procurement",
            "stage": "Series C",
            "funding_total": "$292M",
            "team_size": 250,
            "founded_year": 2020,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Pearl", "Tiger Global", "YC"],
            "industry_tags": ["Procurement", "Enterprise SaaS", "Fintech"],
            "founders": [
                {"name": "Rujul Zaparde", "title": "CEO", "linkedin": "https://linkedin.com/in/rujulzaparde", "twitter": "https://twitter.com/rujulzaparde"},
                {"name": "Lu Cheng", "title": "CTO", "linkedin": "https://linkedin.com/in/lucheng"},
            ],
            "roles": [
                {"title": "Full-Stack Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "hybrid"},
                {"title": "Senior Product Manager", "category": "GTM", "level": "Senior", "visa": "No", "salary": "$170K–$260K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Groq",
            "company_website": "https://groq.com",
            "company_slug": "groq",
            "stage": "Series D",
            "funding_total": "$640M",
            "team_size": 250,
            "founded_year": 2016,
            "country": "US",
            "city": "Mountain View",
            "vc_backers": ["a16z", "Tiger Global", "Samsung"],
            "industry_tags": ["AI", "Semiconductors", "LPU", "Cloud"],
            "founders": [
                {"name": "Jonathan Ross", "title": "CEO", "linkedin": "https://linkedin.com/in/jonathanross", "twitter": "https://twitter.com/JonathanRoss321"},
            ],
            "roles": [
                {"title": "Chip Design Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "onsite"},
                {"title": "ML Systems Engineer", "category": "AI/ML", "level": "Mid", "visa": "Yes", "salary": "$170K–$280K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Mercury",
            "company_website": "https://mercury.com",
            "company_slug": "mercury",
            "stage": "Series C",
            "funding_total": "$163M",
            "team_size": 500,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Sequoia", "Coatue"],
            "industry_tags": ["Fintech", "Banking", "Startup Banking"],
            "founders": [
                {"name": "Immad Akhund", "title": "CEO", "linkedin": "https://linkedin.com/in/immadakhund", "twitter": "https://twitter.com/immad"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$270K", "work_type": "remote"},
                {"title": "Risk Analyst", "category": "Data", "level": "Mid", "visa": "No", "salary": "$120K–$170K", "work_type": "remote"},
            ],
        },
        {
            "company_name": "Runway",
            "company_website": "https://runwayml.com",
            "company_slug": "runway",
            "stage": "Series C",
            "funding_total": "$237M",
            "team_size": 150,
            "founded_year": 2018,
            "country": "US",
            "city": "New York",
            "vc_backers": ["Lightspeed", "Felicis", "Lux Capital"],
            "industry_tags": ["AI", "Video Generation", "Creative Tools"],
            "founders": [
                {"name": "Cristóbal Valenzuela", "title": "CEO", "linkedin": "https://linkedin.com/in/cristobalvalenzuela", "twitter": "https://twitter.com/c_valenzuelab"},
                {"name": "Anastasis Germanidis", "title": "CTO", "linkedin": "https://linkedin.com/in/anastasisg"},
                {"name": "Alejandro Matamala", "title": "COO", "linkedin": "https://linkedin.com/in/alejandro-matamala-b6a0b936"},
            ],
            "roles": [
                {"title": "Research Engineer — Video Models", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$350K", "work_type": "hybrid"},
                {"title": "Frontend Engineer — React", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "hybrid"},
            ],
        },
        # ── India-based startups ──────────────────────────
        {
            "company_name": "Razorpay",
            "company_website": "https://razorpay.com",
            "company_slug": "razorpay",
            "stage": "Series F",
            "funding_total": "$741M",
            "team_size": 3000,
            "founded_year": 2014,
            "country": "India",
            "city": "Bangalore",
            "vc_backers": ["Sequoia", "GIC", "Tiger Global", "Ribbit Capital"],
            "industry_tags": ["Fintech", "Payments", "Banking"],
            "founders": [
                {"name": "Harshil Mathur", "title": "CEO", "linkedin": "https://linkedin.com/in/harshilmathur", "twitter": "https://twitter.com/haraborsilm"},
                {"name": "Shashank Kumar", "title": "CTO", "linkedin": "https://linkedin.com/in/shashank-kumar-razorpay"},
            ],
            "roles": [
                {"title": "Backend Engineer — Payments", "category": "Engineering", "level": "Mid", "visa": "No", "salary": "₹20L–₹45L", "work_type": "hybrid"},
                {"title": "Senior Data Engineer", "category": "Data", "level": "Senior", "visa": "No", "salary": "₹30L–₹60L", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Zerodha",
            "company_website": "https://zerodha.com",
            "company_slug": "zerodha",
            "stage": "Growth",
            "funding_total": "Bootstrapped",
            "team_size": 1200,
            "founded_year": 2010,
            "country": "India",
            "city": "Bangalore",
            "vc_backers": [],
            "industry_tags": ["Fintech", "Stock Trading", "Investment"],
            "founders": [
                {"name": "Nithin Kamath", "title": "CEO", "linkedin": "https://linkedin.com/in/nithinkamath", "twitter": "https://twitter.com/Nithin0dha"},
                {"name": "Nikhil Kamath", "title": "Co-founder", "linkedin": "https://linkedin.com/in/nikhilkamath", "twitter": "https://twitter.com/niaborlkamath"},
            ],
            "roles": [
                {"title": "Senior Go Developer", "category": "Engineering", "level": "Senior", "visa": "No", "salary": "₹25L–₹50L", "work_type": "onsite"},
            ],
        },
        # ── UK / EU startups ──────────────────────────────
        {
            "company_name": "Revolut",
            "company_website": "https://revolut.com",
            "company_slug": "revolut",
            "stage": "Growth",
            "funding_total": "$1.7B",
            "team_size": 8000,
            "founded_year": 2015,
            "country": "UK",
            "city": "London",
            "vc_backers": ["Softbank", "Tiger Global", "DST Global"],
            "industry_tags": ["Fintech", "Neobank", "Payments"],
            "founders": [
                {"name": "Nikolay Storonsky", "title": "CEO", "linkedin": "https://linkedin.com/in/nikolay-storonsky", "twitter": "https://twitter.com/nstoronsky"},
                {"name": "Vlad Yatsenko", "title": "CTO", "linkedin": "https://linkedin.com/in/vladyslavyatsenko"},
            ],
            "roles": [
                {"title": "Backend Engineer — Java", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "£70K–£120K", "work_type": "hybrid"},
                {"title": "Senior Product Manager", "category": "GTM", "level": "Senior", "visa": "Yes", "salary": "£90K–£140K", "work_type": "hybrid"},
            ],
        },
        {
            "company_name": "Monzo",
            "company_website": "https://monzo.com",
            "company_slug": "monzo",
            "stage": "Series H",
            "funding_total": "$610M",
            "team_size": 3000,
            "founded_year": 2015,
            "country": "UK",
            "city": "London",
            "vc_backers": ["a16z", "Accel", "GV", "Passion Capital"],
            "industry_tags": ["Fintech", "Neobank", "Consumer"],
            "founders": [
                {"name": "Tom Blomfield", "title": "Founder", "linkedin": "https://linkedin.com/in/tomblomfield", "twitter": "https://twitter.com/t_blom"},
            ],
            "roles": [
                {"title": "iOS Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "£65K–£100K", "work_type": "hybrid"},
                {"title": "Financial Crime Analyst", "category": "Ops", "level": "Mid", "visa": "Yes", "salary": "£45K–£65K", "work_type": "hybrid"},
            ],
        },
    ]

    jobs: list[Job] = []
    for startup in startups:
        founders = [
            Founder(
                name=f.get("name", ""),
                title=f.get("title", ""),
                linkedin=f.get("linkedin"),
                twitter=f.get("twitter"),
                email=f.get("email"),
                source="diverse_seed",
            )
            for f in startup.get("founders", [])
        ]

        for role in startup.get("roles", []):
            job = Job(
                company_name=startup["company_name"],
                company_website=startup.get("company_website"),
                company_slug=startup["company_slug"],
                stage=startup.get("stage"),
                funding_total=startup.get("funding_total"),
                team_size=startup.get("team_size"),
                founded_year=startup.get("founded_year"),
                country=startup.get("country"),
                city=startup.get("city"),
                vc_backers=startup.get("vc_backers", []),
                industry_tags=startup.get("industry_tags", []),
                founders=founders,
                role_title=role["title"],
                role_category=role.get("category"),
                experience_level=role.get("level"),
                visa_sponsorship=role.get("visa", "Unknown"),
                salary_range=role.get("salary"),
                work_type=role.get("work_type"),
                job_url=startup.get("company_website", "") + "/careers",
                source="diverse_seed",
                status="active",
                is_hiring=True,
                relevance_score=0.75,
            )
            job.generate_id()
            jobs.append(job)

    return jobs
