"""Extra Diverse Startup Seeds — Frontend, Backend, DevOps, Mobile, Blockchain, Biotech, Climate, Gaming, EdTech, HealthTech, Cybersecurity."""
from __future__ import annotations
from models import Job, Founder


def get_extra_seed_jobs() -> list[Job]:
    """Return additional curated startups across diverse categories."""
    startups = [
        # ── FRONTEND / DESIGN TOOLS ──────────────────────
        {
            "company_name": "Framer",
            "company_website": "https://framer.com",
            "company_slug": "framer",
            "stage": "Series C",
            "funding_total": "$140M",
            "team_size": 200,
            "founded_year": 2014,
            "country": "Netherlands",
            "city": "Amsterdam",
            "vc_backers": ["Accel", "Alkeon Capital"],
            "industry_tags": ["Frontend", "Design Tools", "No-Code"],
            "founders": [
                {"name": "Koen Bok", "title": "CEO", "linkedin": "https://linkedin.com/in/koenbok", "twitter": "https://twitter.com/kaborenbok"},
                {"name": "Jorn van Dijk", "title": "CTO", "linkedin": "https://linkedin.com/in/jornvandijk", "twitter": "https://twitter.com/jornvandijk"},
            ],
            "roles": [
                {"title": "Senior Frontend Engineer — React", "category": "Frontend", "level": "Senior", "visa": "Yes", "salary": "€80K–€130K", "work_type": "hybrid", "description": "Build high-performance React components for Framer's visual design editor. Work on Canvas rendering, real-time collaboration, and component library architecture."},
                {"title": "Frontend Engineer — Animations", "category": "Frontend", "level": "Mid", "visa": "Yes", "salary": "€65K–€100K", "work_type": "hybrid", "description": "Create stunning animation systems using Framer Motion. Work on timeline editors, gesture handling, and GPU-accelerated transitions."},
                {"title": "UX Engineer", "category": "Design", "level": "Mid", "visa": "Yes", "salary": "€60K–€95K", "work_type": "remote", "description": "Bridge design and engineering by building pixel-perfect UI components and prototyping new interaction patterns."},
            ],
        },
        {
            "company_name": "Storybook (Chromatic)",
            "company_website": "https://chromatic.com",
            "company_slug": "chromatic",
            "stage": "Series A",
            "funding_total": "$25M",
            "team_size": 50,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Tundra Ventures"],
            "industry_tags": ["Frontend", "Developer Tools", "Open Source"],
            "founders": [
                {"name": "Dominic Nguyen", "title": "CEO", "linkedin": "https://linkedin.com/in/domyen", "twitter": "https://twitter.com/domyen"},
                {"name": "Tom Coleman", "title": "CTO", "linkedin": "https://linkedin.com/in/tmeasday", "twitter": "https://twitter.com/tmeasday"},
            ],
            "roles": [
                {"title": "Frontend Engineer — Storybook Core", "category": "Frontend", "level": "Mid", "visa": "Yes", "salary": "$140K–$200K", "work_type": "remote", "description": "Contribute to the Storybook open-source project. Build addon APIs, webpack/vite integrations, and component testing frameworks."},
            ],
        },
        {
            "company_name": "Builder.io",
            "company_website": "https://builder.io",
            "company_slug": "builder-io",
            "stage": "Series B",
            "funding_total": "$95M",
            "team_size": 120,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Bessemer", "Greylock", "M12"],
            "industry_tags": ["Frontend", "Visual CMS", "No-Code"],
            "founders": [
                {"name": "Steve Sewell", "title": "CEO", "linkedin": "https://linkedin.com/in/stevesewell", "twitter": "https://twitter.com/AboSteveSewell"},
            ],
            "roles": [
                {"title": "Senior React/Next.js Engineer", "category": "Frontend", "level": "Senior", "visa": "Yes", "salary": "$180K–$260K", "work_type": "remote", "description": "Build Builder's Visual CMS using React, Next.js, and Qwik. Work on drag-and-drop page building, A/B testing, and content management."},
                {"title": "Developer Experience Engineer", "category": "Frontend", "level": "Mid", "visa": "No", "salary": "$140K–$200K", "work_type": "remote", "description": "Create SDKs, documentation, and example apps for Builder.io integrations with React, Vue, Angular, and Svelte."},
            ],
        },
        # ── BACKEND / INFRASTRUCTURE ─────────────────────
        {
            "company_name": "PlanetScale",
            "company_website": "https://planetscale.com",
            "company_slug": "planetscale",
            "stage": "Series C",
            "funding_total": "$105M",
            "team_size": 180,
            "founded_year": 2018,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "SignalFire", "Insight Partners"],
            "industry_tags": ["Backend", "Database", "MySQL", "Infrastructure"],
            "founders": [
                {"name": "Jiten Vaidya", "title": "CEO", "linkedin": "https://linkedin.com/in/jitenvaidya", "twitter": "https://twitter.com/jitenvaidya"},
                {"name": "Sugu Sougoumarane", "title": "CTO", "linkedin": "https://linkedin.com/in/ssougou", "twitter": "https://twitter.com/ssougou"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer — Vitess", "category": "Backend", "level": "Senior", "visa": "Yes", "salary": "$190K–$300K", "work_type": "remote", "description": "Work on Vitess, the massively-scaled MySQL clustering system. Build sharding, replication, and schema migration infrastructure."},
                {"title": "Backend Engineer — Go", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "remote", "description": "Build PlanetScale's control plane APIs in Go. Work on database provisioning, branching, and deploy request workflows."},
            ],
        },
        {
            "company_name": "Neon",
            "company_website": "https://neon.tech",
            "company_slug": "neon",
            "stage": "Series B",
            "funding_total": "$104M",
            "team_size": 120,
            "founded_year": 2021,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["GV", "Menlo Ventures", "Founders Fund"],
            "industry_tags": ["Backend", "Serverless Postgres", "Database"],
            "founders": [
                {"name": "Nikita Shamgunov", "title": "CEO", "linkedin": "https://linkedin.com/in/nikitashamgunov", "twitter": "https://twitter.com/nikitabase"},
                {"name": "Heikki Linnakangas", "title": "Co-founder", "linkedin": "https://linkedin.com/in/heikkilinnakangas"},
                {"name": "Stas Kelvich", "title": "Co-founder", "linkedin": "https://linkedin.com/in/staskelvich"},
            ],
            "roles": [
                {"title": "Systems Engineer — Postgres", "category": "Backend", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "remote", "description": "Work on Neon's serverless Postgres storage engine. Build page server, WAL processing, and compute-storage separation layers in Rust."},
                {"title": "Backend Engineer — Control Plane", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "remote", "description": "Build Neon's cloud management API. Work on autoscaling, branching, and multi-tenant orchestration in Rust and Go."},
            ],
        },
        {
            "company_name": "Temporal",
            "company_website": "https://temporal.io",
            "company_slug": "temporal",
            "stage": "Series B",
            "funding_total": "$246M",
            "team_size": 200,
            "founded_year": 2019,
            "country": "US",
            "city": "Seattle",
            "vc_backers": ["Sequoia", "Greenoaks", "Madrona"],
            "industry_tags": ["Backend", "Workflow Orchestration", "Open Source"],
            "founders": [
                {"name": "Maxim Fateev", "title": "CEO", "linkedin": "https://linkedin.com/in/fateev", "twitter": "https://twitter.com/maboraxfateev"},
                {"name": "Samar Abbas", "title": "CTO", "linkedin": "https://linkedin.com/in/samarabbas"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer — Go", "category": "Backend", "level": "Senior", "visa": "Yes", "salary": "$200K–$310K", "work_type": "remote", "description": "Build Temporal's durable execution engine in Go. Work on workflow scheduling, event sourcing, and multi-cluster replication."},
                {"title": "SDK Engineer — TypeScript", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "remote", "description": "Develop and maintain Temporal's TypeScript SDK. Build workflow client APIs, interceptors, and testing utilities."},
            ],
        },
        # ── DEVOPS / CLOUD ───────────────────────────────
        {
            "company_name": "Pulumi",
            "company_website": "https://pulumi.com",
            "company_slug": "pulumi",
            "stage": "Series C",
            "funding_total": "$97M",
            "team_size": 150,
            "founded_year": 2017,
            "country": "US",
            "city": "Seattle",
            "vc_backers": ["NEA", "Madrona", "Tola Capital"],
            "industry_tags": ["DevOps", "Infrastructure as Code", "Cloud"],
            "founders": [
                {"name": "Joe Duffy", "title": "CEO", "linkedin": "https://linkedin.com/in/joejduffy", "twitter": "https://twitter.com/funaborcooljoe"},
                {"name": "Eric Rudder", "title": "Executive Chairman", "linkedin": "https://linkedin.com/in/ericrudder"},
            ],
            "roles": [
                {"title": "Senior DevOps Engineer", "category": "DevOps", "level": "Senior", "visa": "Yes", "salary": "$180K–$270K", "work_type": "remote", "description": "Build Pulumi's cloud infrastructure platform. Work on provider plugins for AWS/Azure/GCP, policy engines, and deployment automation."},
                {"title": "Platform Engineer — Kubernetes", "category": "DevOps", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "remote", "description": "Build Kubernetes operator integrations and Helm chart support. Work on cloud-native deployment workflows."},
            ],
        },
        {
            "company_name": "Teleport",
            "company_website": "https://goteleport.com",
            "company_slug": "teleport",
            "stage": "Series C",
            "funding_total": "$169M",
            "team_size": 250,
            "founded_year": 2015,
            "country": "US",
            "city": "Oakland",
            "vc_backers": ["Bessemer", "Kleiner Perkins", "S28 Capital"],
            "industry_tags": ["DevOps", "Cybersecurity", "Infrastructure Access"],
            "founders": [
                {"name": "Ev Kontsevoy", "title": "CEO", "linkedin": "https://linkedin.com/in/kontsevoy", "twitter": "https://twitter.com/kontsevoy"},
                {"name": "Alexander Klizhentas", "title": "CTO", "linkedin": "https://linkedin.com/in/klizhentas"},
                {"name": "Taylor Wakefield", "title": "COO", "linkedin": "https://linkedin.com/in/taylorwakefield"},
            ],
            "roles": [
                {"title": "Senior Go Engineer — Access Control", "category": "DevOps", "level": "Senior", "visa": "Yes", "salary": "$190K–$280K", "work_type": "remote", "description": "Build zero-trust access infrastructure in Go. Work on SSH/Kubernetes/database proxying and identity-based authorization."},
                {"title": "Site Reliability Engineer", "category": "DevOps", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "remote", "description": "Manage Teleport Cloud infrastructure. Build observability pipelines, incident response automation, and capacity planning."},
            ],
        },
        # ── MOBILE ───────────────────────────────────────
        {
            "company_name": "Expo",
            "company_website": "https://expo.dev",
            "company_slug": "expo",
            "stage": "Series B",
            "funding_total": "$50M",
            "team_size": 80,
            "founded_year": 2016,
            "country": "US",
            "city": "Palo Alto",
            "vc_backers": ["Arrowhead", "Tonic Capital"],
            "industry_tags": ["Mobile", "React Native", "Developer Tools"],
            "founders": [
                {"name": "Charlie Cheever", "title": "CEO", "linkedin": "https://linkedin.com/in/ccheever", "twitter": "https://twitter.com/ccheever"},
                {"name": "James Ide", "title": "CTO", "linkedin": "https://linkedin.com/in/jamespaul", "twitter": "https://twitter.com/ji"},
            ],
            "roles": [
                {"title": "React Native Engineer", "category": "Mobile", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "remote", "description": "Build Expo's React Native development platform. Work on EAS Build, OTA updates, and native module bridging."},
                {"title": "Senior Mobile Engineer — iOS/Android", "category": "Mobile", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "remote", "description": "Build native iOS and Android libraries for Expo modules. Work on camera, file system, notifications, and other native APIs."},
            ],
        },
        {
            "company_name": "RevenueCat",
            "company_website": "https://revenuecat.com",
            "company_slug": "revenuecat",
            "stage": "Series C",
            "funding_total": "$56M",
            "team_size": 100,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Insight Partners", "Index Ventures"],
            "industry_tags": ["Mobile", "Subscriptions", "SDK"],
            "founders": [
                {"name": "Jacob Eiting", "title": "CEO", "linkedin": "https://linkedin.com/in/jeiting", "twitter": "https://twitter.com/jeiting"},
                {"name": "Miguel Carranza", "title": "CTO", "linkedin": "https://linkedin.com/in/miguelcarranza", "twitter": "https://twitter.com/imiguelcarranza"},
            ],
            "roles": [
                {"title": "iOS SDK Engineer — Swift", "category": "Mobile", "level": "Senior", "visa": "Yes", "salary": "$180K–$260K", "work_type": "remote", "description": "Maintain RevenueCat's iOS SDK used by 30K+ apps. Work on StoreKit 2 integration, receipt validation, and entitlement management."},
                {"title": "Android Engineer — Kotlin", "category": "Mobile", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "remote", "description": "Build and maintain the Android SDK. Work on Google Play Billing Library integration, subscription analytics, and cross-platform parity."},
            ],
        },
        # ── BLOCKCHAIN / WEB3 ────────────────────────────
        {
            "company_name": "Alchemy",
            "company_website": "https://alchemy.com",
            "company_slug": "alchemy",
            "stage": "Series C",
            "funding_total": "$345M",
            "team_size": 200,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Lightspeed", "Silver Lake"],
            "industry_tags": ["Blockchain", "Web3", "Developer Tools"],
            "founders": [
                {"name": "Nikil Viswanathan", "title": "CEO", "linkedin": "https://linkedin.com/in/nikil", "twitter": "https://twitter.com/niaborlcrypto"},
                {"name": "Joe Lau", "title": "CTO", "linkedin": "https://linkedin.com/in/joeylau", "twitter": "https://twitter.com/joeylau_"},
            ],
            "roles": [
                {"title": "Senior Blockchain Engineer", "category": "Blockchain", "level": "Senior", "visa": "Yes", "salary": "$200K–$350K", "work_type": "hybrid", "description": "Build Alchemy's blockchain infrastructure APIs. Work on node management, transaction simulation, and multi-chain indexing."},
                {"title": "Smart Contract Engineer — Solidity", "category": "Blockchain", "level": "Mid", "visa": "Yes", "salary": "$170K–$280K", "work_type": "remote", "description": "Develop smart contract tooling and Account Abstraction SDKs. Build gas estimation, contract verification, and deployment pipelines."},
            ],
        },
        {
            "company_name": "Chainalysis",
            "company_website": "https://chainalysis.com",
            "company_slug": "chainalysis",
            "stage": "Series F",
            "funding_total": "$536M",
            "team_size": 900,
            "founded_year": 2014,
            "country": "US",
            "city": "New York",
            "vc_backers": ["Benchmark", "Accel", "GIC"],
            "industry_tags": ["Blockchain", "Compliance", "Analytics"],
            "founders": [
                {"name": "Michael Gronager", "title": "CEO", "linkedin": "https://linkedin.com/in/gronager", "twitter": "https://twitter.com/gronager"},
                {"name": "Jonathan Levin", "title": "CSO", "linkedin": "https://linkedin.com/in/jonathanmlevin", "twitter": "https://twitter.com/jabornathanlevin"},
            ],
            "roles": [
                {"title": "Backend Engineer — Blockchain Data", "category": "Blockchain", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "hybrid", "description": "Build blockchain data pipelines for transaction analysis. Work on graph algorithms, entity clustering, and cross-chain tracking."},
                {"title": "Senior Data Engineer", "category": "Data", "level": "Senior", "visa": "Yes", "salary": "$185K–$280K", "work_type": "hybrid", "description": "Build large-scale data systems processing billions of blockchain transactions. Work on real-time streaming, data warehousing, and ML feature pipelines."},
            ],
        },
        # ── BIOTECH / HEALTHTECH ─────────────────────────
        {
            "company_name": "Recursion",
            "company_website": "https://recursion.com",
            "company_slug": "recursion",
            "stage": "Growth",
            "funding_total": "$1.5B",
            "team_size": 800,
            "founded_year": 2013,
            "country": "US",
            "city": "Salt Lake City",
            "vc_backers": ["Baillie Gifford", "SoftBank", "NVIDIA"],
            "industry_tags": ["Biotech", "AI Drug Discovery", "HealthTech"],
            "founders": [
                {"name": "Chris Gibson", "title": "CEO", "linkedin": "https://linkedin.com/in/chrisgibson", "twitter": "https://twitter.com/chrisgibsonphd"},
                {"name": "Dean Li", "title": "Co-founder", "linkedin": "https://linkedin.com/in/deanyli"},
            ],
            "roles": [
                {"title": "ML Engineer — Drug Discovery", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$185K–$290K", "work_type": "hybrid", "description": "Build ML models for drug target identification using cellular imaging data. Work on computer vision, generative chemistry, and phenotypic screening."},
                {"title": "Bioinformatics Engineer", "category": "Data", "level": "Mid", "visa": "Yes", "salary": "$140K–$210K", "work_type": "hybrid", "description": "Build bioinformatics pipelines for genomics and proteomics data. Work on variant calling, gene expression analysis, and multi-omics integration."},
            ],
        },
        {
            "company_name": "Viz.ai",
            "company_website": "https://viz.ai",
            "company_slug": "viz-ai",
            "stage": "Series D",
            "funding_total": "$252M",
            "team_size": 350,
            "founded_year": 2016,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Insight Partners", "Tiger Global", "Greenoaks"],
            "industry_tags": ["HealthTech", "AI", "Medical Imaging"],
            "founders": [
                {"name": "Chris Mansi", "title": "CEO", "linkedin": "https://linkedin.com/in/chrismansi", "twitter": "https://twitter.com/drmansi"},
                {"name": "David Golan", "title": "CTO", "linkedin": "https://linkedin.com/in/davidgolan"},
            ],
            "roles": [
                {"title": "Computer Vision Engineer — Medical AI", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$190K–$300K", "work_type": "hybrid", "description": "Build FDA-cleared AI algorithms for medical image analysis. Work on stroke detection, pulmonary embolism screening, and cardiac imaging."},
                {"title": "Backend Engineer — HIPAA Systems", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "hybrid", "description": "Build HIPAA-compliant healthcare data systems. Work on HL7/DICOM integrations, clinical notification workflows, and secure cloud infrastructure."},
            ],
        },
        # ── CLIMATE TECH ─────────────────────────────────
        {
            "company_name": "Watershed",
            "company_website": "https://watershed.com",
            "company_slug": "watershed",
            "stage": "Series C",
            "funding_total": "$200M",
            "team_size": 300,
            "founded_year": 2019,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "Kleiner Perkins", "Greenoaks"],
            "industry_tags": ["Climate Tech", "ESG", "Enterprise SaaS"],
            "founders": [
                {"name": "Taylor Francis", "title": "CEO", "linkedin": "https://linkedin.com/in/taylorfrancis", "twitter": "https://twitter.com/tayaborlorfrancis"},
                {"name": "Christian Anderson", "title": "CTO", "linkedin": "https://linkedin.com/in/christiananderson"},
                {"name": "Avi Itskovich", "title": "VP Engineering", "linkedin": "https://linkedin.com/in/avii"},
            ],
            "roles": [
                {"title": "Full-Stack Engineer — Carbon Accounting", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "hybrid", "description": "Build Watershed's carbon accounting platform. Work on emissions data modeling, supply chain tracking, and regulatory compliance reporting."},
                {"title": "Data Scientist — Climate", "category": "Data", "level": "Senior", "visa": "Yes", "salary": "$180K–$270K", "work_type": "hybrid", "description": "Build emissions estimation models and lifecycle analysis tools. Work on Scope 1-3 calculations, benchmarking, and climate scenario modeling."},
            ],
        },
        # ── GAMING / ENTERTAINMENT ───────────────────────
        {
            "company_name": "Inworld AI",
            "company_website": "https://inworld.ai",
            "company_slug": "inworld-ai",
            "stage": "Series A",
            "funding_total": "$120M",
            "team_size": 100,
            "founded_year": 2021,
            "country": "US",
            "city": "Mountain View",
            "vc_backers": ["Lightspeed", "Intel Capital", "Microsoft M12"],
            "industry_tags": ["Gaming", "AI", "NPCs", "Metaverse"],
            "founders": [
                {"name": "Ilya Gelfenbeyn", "title": "CEO", "linkedin": "https://linkedin.com/in/gelfenbeyn", "twitter": "https://twitter.com/gelfenbeyn"},
                {"name": "Michael Ermolenko", "title": "CTO", "linkedin": "https://linkedin.com/in/ermolenko"},
            ],
            "roles": [
                {"title": "Game Engine Engineer — Unreal/Unity", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid", "description": "Build AI NPC integration SDKs for Unreal Engine and Unity. Work on real-time character behavior, dialogue systems, and emotion models."},
                {"title": "ML Engineer — Conversational AI", "category": "AI/ML", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "hybrid", "description": "Train and deploy conversational AI models for game NPCs. Work on personality systems, context awareness, and low-latency inference."},
            ],
        },
        # ── EDTECH ───────────────────────────────────────
        {
            "company_name": "Replit",
            "company_website": "https://replit.com",
            "company_slug": "replit",
            "stage": "Series B",
            "funding_total": "$222M",
            "team_size": 200,
            "founded_year": 2016,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Khosla Ventures", "Coatue"],
            "industry_tags": ["EdTech", "IDE", "AI", "Developer Tools"],
            "founders": [
                {"name": "Amjad Masad", "title": "CEO", "linkedin": "https://linkedin.com/in/amjadmasad", "twitter": "https://twitter.com/amasad"},
                {"name": "Faris Masad", "title": "CTO", "linkedin": "https://linkedin.com/in/farismasad"},
                {"name": "Haya Odeh", "title": "Head of Design", "linkedin": "https://linkedin.com/in/hayaodeh"},
            ],
            "roles": [
                {"title": "Senior Engineer — Code Intelligence", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "hybrid", "description": "Build Replit's AI-powered coding features. Work on code completion, debugging assistance, and natural language to code generation."},
                {"title": "Infrastructure Engineer — Nix/Containers", "category": "DevOps", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "hybrid", "description": "Build Replit's container runtime and Nix package management. Work on workspace isolation, fast boot times, and language server integration."},
            ],
        },
        # ── CYBERSECURITY ────────────────────────────────
        {
            "company_name": "Snyk",
            "company_website": "https://snyk.io",
            "company_slug": "snyk",
            "stage": "Series G",
            "funding_total": "$1.3B",
            "team_size": 1500,
            "founded_year": 2015,
            "country": "UK",
            "city": "London",
            "vc_backers": ["Accel", "Tiger Global", "Addition", "Coatue"],
            "industry_tags": ["Cybersecurity", "DevSecOps", "Developer Tools"],
            "founders": [
                {"name": "Guy Podjarny", "title": "Founder", "linkedin": "https://linkedin.com/in/guypo", "twitter": "https://twitter.com/guypod"},
                {"name": "Assaf Hefetz", "title": "Co-founder", "linkedin": "https://linkedin.com/in/assafhefetz"},
                {"name": "Danny Grander", "title": "Co-founder", "linkedin": "https://linkedin.com/in/dannygrander"},
            ],
            "roles": [
                {"title": "Security Researcher — SAST", "category": "Cybersecurity", "level": "Senior", "visa": "Yes", "salary": "£80K–£130K", "work_type": "hybrid", "description": "Research and build static application security testing rules. Analyze vulnerability patterns across languages and develop detection algorithms."},
                {"title": "Backend Engineer — Vulnerability DB", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "£65K–£100K", "work_type": "hybrid", "description": "Build and maintain Snyk's vulnerability database. Work on CVE aggregation, package ecosystem crawling, and fix recommendation engines."},
            ],
        },
        {
            "company_name": "CrowdStrike",
            "company_website": "https://crowdstrike.com",
            "company_slug": "crowdstrike",
            "stage": "Growth",
            "funding_total": "$481M",
            "team_size": 8000,
            "founded_year": 2011,
            "country": "US",
            "city": "Austin",
            "vc_backers": ["Accel", "Warburg Pincus", "March Capital"],
            "industry_tags": ["Cybersecurity", "Endpoint Security", "Cloud Security"],
            "founders": [
                {"name": "George Kurtz", "title": "CEO", "linkedin": "https://linkedin.com/in/georgekurtz", "twitter": "https://twitter.com/George_Kurtz"},
                {"name": "Dmitri Alperovitch", "title": "Co-founder", "linkedin": "https://linkedin.com/in/dalperovitch", "twitter": "https://twitter.com/DAlperovitch"},
            ],
            "roles": [
                {"title": "Threat Intelligence Engineer", "category": "Cybersecurity", "level": "Senior", "visa": "Yes", "salary": "$170K–$270K", "work_type": "hybrid", "description": "Analyze advanced threat actors and develop detection signatures. Work on malware reverse engineering, exploit analysis, and threat hunting."},
                {"title": "Cloud Security Engineer", "category": "Cybersecurity", "level": "Mid", "visa": "Yes", "salary": "$150K–$240K", "work_type": "hybrid", "description": "Build cloud workload protection features. Work on container security, serverless monitoring, and CSPM rule engines."},
            ],
        },
        # ── MORE AI/ML STARTUPS ──────────────────────────
        {
            "company_name": "Weights & Biases",
            "company_website": "https://wandb.ai",
            "company_slug": "wandb",
            "stage": "Series C",
            "funding_total": "$250M",
            "team_size": 300,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Insight Partners", "Tiger Global", "a16z"],
            "industry_tags": ["AI/ML", "MLOps", "Developer Tools"],
            "founders": [
                {"name": "Lukas Biewald", "title": "CEO", "linkedin": "https://linkedin.com/in/lukasbiewald", "twitter": "https://twitter.com/l2k"},
                {"name": "Chris Van Pelt", "title": "CTO", "linkedin": "https://linkedin.com/in/vanpelt", "twitter": "https://twitter.com/vanpelt"},
                {"name": "Shawn Lewis", "title": "Co-founder", "linkedin": "https://linkedin.com/in/shawnrlewis"},
            ],
            "roles": [
                {"title": "ML Platform Engineer", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$200K–$310K", "work_type": "hybrid", "description": "Build W&B's experiment tracking and model registry. Work on distributed training logging, hyperparameter optimization, and artifact versioning."},
                {"title": "Frontend Engineer — Data Viz", "category": "Frontend", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "hybrid", "description": "Build interactive dashboards for ML experiment visualization. Work on charts, comparison tables, and collaborative reporting tools using React and D3."},
            ],
        },
        {
            "company_name": "Replicate",
            "company_website": "https://replicate.com",
            "company_slug": "replicate",
            "stage": "Series B",
            "funding_total": "$60M",
            "team_size": 40,
            "founded_year": 2019,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Y Combinator"],
            "industry_tags": ["AI/ML", "MLOps", "API"],
            "founders": [
                {"name": "Ben Firshman", "title": "CEO", "linkedin": "https://linkedin.com/in/bfirsh", "twitter": "https://twitter.com/bfirsh"},
                {"name": "Andreas Jansson", "title": "CTO", "linkedin": "https://linkedin.com/in/andreasjansson", "twitter": "https://twitter.com/andreasjansson"},
            ],
            "roles": [
                {"title": "Infrastructure Engineer — GPU Orchestration", "category": "DevOps", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "remote", "description": "Build Replicate's GPU orchestration platform. Work on multi-cloud GPU scheduling, container runtime optimization, and autoscaling."},
                {"title": "Full-Stack Engineer", "category": "Engineering", "level": "Mid", "visa": "Yes", "salary": "$160K–$250K", "work_type": "remote", "description": "Build Replicate's web application and API. Work on model deployment UI, prediction dashboards, and billing system."},
            ],
        },
        # ── FINTECH (DIVERSE) ────────────────────────────
        {
            "company_name": "Plaid",
            "company_website": "https://plaid.com",
            "company_slug": "plaid",
            "stage": "Series D",
            "funding_total": "$734M",
            "team_size": 1200,
            "founded_year": 2013,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Index Ventures", "Spark Capital", "NEA"],
            "industry_tags": ["Fintech", "Banking API", "Open Finance"],
            "founders": [
                {"name": "Zach Perret", "title": "CEO", "linkedin": "https://linkedin.com/in/zachperret", "twitter": "https://twitter.com/zachperret"},
                {"name": "William Hockey", "title": "Co-founder", "linkedin": "https://linkedin.com/in/williamhockey"},
            ],
            "roles": [
                {"title": "Backend Engineer — Financial Data", "category": "Backend", "level": "Mid", "visa": "Yes", "salary": "$170K–$260K", "work_type": "hybrid", "description": "Build Plaid's financial data aggregation APIs. Work on bank connections, transaction categorization, and real-time balance checks."},
                {"title": "Senior Security Engineer", "category": "Cybersecurity", "level": "Senior", "visa": "Yes", "salary": "$200K–$310K", "work_type": "hybrid", "description": "Build security infrastructure for financial data. Work on encryption, access controls, SOC 2 compliance, and incident response."},
            ],
        },
        {
            "company_name": "Brex",
            "company_website": "https://brex.com",
            "company_slug": "brex",
            "stage": "Series D",
            "funding_total": "$1.2B",
            "team_size": 1200,
            "founded_year": 2017,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Greenoaks", "Tiger Global", "Y Combinator"],
            "industry_tags": ["Fintech", "Corporate Cards", "Expense Management"],
            "founders": [
                {"name": "Henrique Dubugras", "title": "CEO", "linkedin": "https://linkedin.com/in/hdubugras", "twitter": "https://twitter.com/hdubugras"},
                {"name": "Pedro Franceschi", "title": "CTO", "linkedin": "https://linkedin.com/in/pedrofranceschi", "twitter": "https://twitter.com/pedroof"},
            ],
            "roles": [
                {"title": "Senior Backend Engineer — Payments", "category": "Backend", "level": "Senior", "visa": "Yes", "salary": "$190K–$300K", "work_type": "hybrid", "description": "Build Brex's real-time payment processing systems. Work on card authorization, settlement, and ledger management."},
                {"title": "Frontend Engineer — Dashboard", "category": "Frontend", "level": "Mid", "visa": "Yes", "salary": "$160K–$240K", "work_type": "hybrid", "description": "Build Brex's financial dashboard using React. Work on expense reporting, budgeting tools, and real-time transaction feeds."},
            ],
        },
        # ── LOGISTICS / SUPPLY CHAIN ─────────────────────
        {
            "company_name": "Flexport",
            "company_website": "https://flexport.com",
            "company_slug": "flexport",
            "stage": "Series E",
            "funding_total": "$2.3B",
            "team_size": 3000,
            "founded_year": 2013,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Founders Fund", "DST Global", "SoftBank"],
            "industry_tags": ["Logistics", "Supply Chain", "Trade"],
            "founders": [
                {"name": "Ryan Petersen", "title": "CEO", "linkedin": "https://linkedin.com/in/ryanpetersen", "twitter": "https://twitter.com/typesfast"},
            ],
            "roles": [
                {"title": "Senior Full-Stack Engineer — Trade OS", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$180K–$280K", "work_type": "hybrid", "description": "Build Flexport's trade management platform. Work on shipment tracking, customs documentation, and real-time logistics dashboards."},
                {"title": "Data Engineer — Supply Chain Analytics", "category": "Data", "level": "Mid", "visa": "Yes", "salary": "$150K–$230K", "work_type": "hybrid", "description": "Build data pipelines for global supply chain analytics. Work on ETA prediction, route optimization, and demand forecasting."},
            ],
        },
        # ── COMMUNICATION / COLLABORATION ────────────────
        {
            "company_name": "Loom",
            "company_website": "https://loom.com",
            "company_slug": "loom",
            "stage": "Acquired",
            "funding_total": "$203M",
            "team_size": 250,
            "founded_year": 2015,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["a16z", "Sequoia", "Kleiner Perkins", "Coatue"],
            "industry_tags": ["Video", "Collaboration", "Async Communication"],
            "founders": [
                {"name": "Joe Thomas", "title": "CEO", "linkedin": "https://linkedin.com/in/jnthms", "twitter": "https://twitter.com/jnthms"},
                {"name": "Vinay Hiremath", "title": "CTO", "linkedin": "https://linkedin.com/in/vhiremath", "twitter": "https://twitter.com/vhmth"},
                {"name": "Shahed Khan", "title": "Co-founder", "linkedin": "https://linkedin.com/in/shahedkhan"},
            ],
            "roles": [
                {"title": "Senior Video Engineer — WebRTC", "category": "Engineering", "level": "Senior", "visa": "Yes", "salary": "$190K–$290K", "work_type": "hybrid", "description": "Build Loom's video recording and playback engine. Work on WebRTC, video encoding/transcoding, and real-time streaming optimization."},
                {"title": "Frontend Engineer — React", "category": "Frontend", "level": "Mid", "visa": "Yes", "salary": "$155K–$230K", "work_type": "hybrid", "description": "Build Loom's video management UI. Work on video player components, commenting systems, and workspace management."},
            ],
        },
        # ── LEGALTECH ────────────────────────────────────
        {
            "company_name": "Harvey AI",
            "company_website": "https://harvey.ai",
            "company_slug": "harvey-ai",
            "stage": "Series C",
            "funding_total": "$206M",
            "team_size": 150,
            "founded_year": 2022,
            "country": "US",
            "city": "San Francisco",
            "vc_backers": ["Sequoia", "Kleiner Perkins", "OpenAI Fund"],
            "industry_tags": ["LegalTech", "AI", "Enterprise"],
            "founders": [
                {"name": "Winston Weinberg", "title": "CEO", "linkedin": "https://linkedin.com/in/winstonweinberg", "twitter": "https://twitter.com/winstonweinberg"},
                {"name": "Gabriel Pereyra", "title": "CTO", "linkedin": "https://linkedin.com/in/gabrielpereyra"},
            ],
            "roles": [
                {"title": "ML Engineer — Legal AI", "category": "AI/ML", "level": "Senior", "visa": "Yes", "salary": "$220K–$370K", "work_type": "hybrid", "description": "Fine-tune and deploy LLMs for legal document analysis. Work on contract review, case law research, and regulatory compliance workflows."},
                {"title": "Senior Backend Engineer", "category": "Backend", "level": "Senior", "visa": "Yes", "salary": "$200K–$320K", "work_type": "hybrid", "description": "Build Harvey's secure document processing pipeline. Work on RAG systems, multi-tenant architecture, and enterprise SSO integration."},
            ],
        },
    ]

    jobs: list[Job] = []
    for startup in startups:
        founders = [
            Founder(
                name=f.get("name", ""),
                title=f.get("title", ""),
                linkedin=f.get("linkedin"),
                twitter=f.get("twitter"),
                email=f.get("email"),
                source="diverse_seed_extra",
            )
            for f in startup.get("founders", [])
        ]

        for role in startup.get("roles", []):
            job = Job(
                company_name=startup["company_name"],
                company_website=startup.get("company_website"),
                company_slug=startup["company_slug"],
                stage=startup.get("stage"),
                funding_total=startup.get("funding_total"),
                team_size=startup.get("team_size"),
                founded_year=startup.get("founded_year"),
                country=startup.get("country"),
                city=startup.get("city"),
                vc_backers=startup.get("vc_backers", []),
                industry_tags=startup.get("industry_tags", []),
                founders=founders,
                role_title=role["title"],
                role_category=role.get("category"),
                experience_level=role.get("level"),
                visa_sponsorship=role.get("visa", "Unknown"),
                salary_range=role.get("salary"),
                work_type=role.get("work_type"),
                job_url=startup.get("company_website", "") + "/careers",
                job_description=role.get("description", ""),
                jd_summary=role.get("description", ""),
                source="diverse_seed_extra",
                status="active",
                is_hiring=True,
                relevance_score=0.78,
            )
            job.generate_id()
            jobs.append(job)

    return jobs
